# Generated by Django 4.2.1 on 2023-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAuth",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pubB", models.TextField(max_length=4096)),
                ("privB", models.TextField(max_length=4096)),
                ("expire_timestamp", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
