# Generated by Django 4.2.1 on 2023-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_pendingauth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.AddField(
            model_name="user",
            name="privKey",
            field=models.TextField(default=None, max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="pubKey",
            field=models.TextField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="salt",
            field=models.TextField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="verifier",
            field=models.TextField(default=None, max_length=4096),
            preserve_default=False,
        ),
    ]
