# Generated by Django 4.2.1 on 2023-05-23 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_user_password_user_privkey_user_pubkey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        6, "the field must contain at least 6 characters"
                    )
                ],
            ),
        ),
    ]
