# Generated by Django 4.2.1 on 2023-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_user_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
