# Generated by Django 4.2.1 on 2023-05-23 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="login",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "the field must contain at least 5 characters"
                    )
                ],
            ),
        ),
    ]
