# Generated by Django 4.2.1 on 2023-05-23 17:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_user_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_key",
            field=models.CharField(
                default=api.models.generate_random_key, max_length=32
            ),
        ),
    ]
