# Generated by Django 4.2.1 on 2023-05-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_session_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingauth",
            name="user",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
            preserve_default=False,
        ),
    ]
