# Generated by Django 4.2.1 on 2023-05-24 16:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_pendingauth_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="expire_timestamp",
            field=models.BigIntegerField(default=api.models.generate_exp_time),
        ),
    ]
