# Generated by Django 4.2.1 on 2023-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_readstate_message"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dialog",
            constraint=models.UniqueConstraint(
                fields=("user_1", "user_2"), name="unique_dialog_between_users"
            ),
        ),
        migrations.AddConstraint(
            model_name="readstate",
            constraint=models.UniqueConstraint(
                fields=("dialog", "user"), name="unique_read_state"
            ),
        ),
    ]
