# Generated by Django 4.2.1 on 2023-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_dialog_unique_dialog_between_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="key_1",
            field=models.TextField(default=None, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dialog",
            name="key_2",
            field=models.TextField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
