# Generated by Django 4.2.1 on 2023-06-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_rename_text_message_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatars"),
        ),
    ]
