# Generated by Django 4.2.2 on 2023-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readstate',
            name='message_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
