class WS_OP:
    SESSION_TERM = -1

    IDENTIFY = 0
    CREATE_MESSAGE = 1
    MARK_AS_READ = 2
    DIALOG_UPDATE = 3
    HEARTBEAT = 4
    HEARTBEAT_ACK = 5
    HELLO = 6
    PRESENCES = 7
    READY = 8


class WSClose:
    INVALID_MESSAGE = 4000
    UNAUTHORIZED = 4001
    TIMEOUT = 4002
